title: GOOD Platform
description: The General Open Orbital Dynamics Platform — Open, FAIR, and reproducible orbital dynamics for the global scientific community.
baseurl: "/good-platform"
url: ""

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Collections
collections:
  team:
    output: false

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
